from __future__ import annotations

from decimal import Decimal
from typing import Protocol

from bistbot.app.models import PaperOrder,RiskDecision,TradeSignal
from bistbot.portfolio.service import PortfolioPosition


class Broker(Protocol):
    def buy(self,signal: TradeSignal,risk_decision: RiskDecision) -> PaperOrder: ...
    def sell(self,signal: TradeSignal,quantity: int,risk_decision: RiskDecision) -> PaperOrder: ...
    def cancel_order(self,order_id: str) -> bool: ...
    def get_orders(self) -> list[PaperOrder]: ...
    def get_positions(self) -> dict[str,PortfolioPosition]: ...
    def get_cash(self) -> Decimal: ...
    def get_portfolio_value(self,prices: dict[str,Decimal]|None=None) -> Decimal: ...


class RealBroker:
    def __init__(self,*args: object,**kwargs: object):
        raise NotImplementedError("Real broker trading disabled in V1")
